using DbManager.Parser;
using System;


namespace DbManager
{
    public class ColumnDefinition
    {
        public enum DataType { String, Int, Double}

        public DataType Type;
        public string Name { get; private set; }


        public ColumnDefinition(DataType type, string name)
        {
            //TODO DEADLINE 1.A: Initialize member variables
            this.Type = type;

            this.Name = name;
        }

        private const string Delimiter = "->";
        private const string DelimiterEncoded = "[ARROW]";

        private static string Encode(string value)
        {
            //TODO DEADLINE 1.C: Encode the delimiter in the value
            if(value == null)
            {
               return null; 
            }
             return value.Replace(Delimiter, DelimiterEncoded);
            
        }

        private static string Decode(string value)
        {
            //TODO DEADLINE 1.C: Decode the delimiter in the value
            if(value == null)
            {
                return null;
            }
            
            return value.Replace(DelimiterEncoded, Delimiter);
        }

        public string AsText()
        {
            //TODO DEADLINE 1.C: Return the column as a string with the name and the type separated by the delimiter
            
            return Encode(Name) + Delimiter + Type.ToString();
            
        }

        public static ColumnDefinition Parse(string value)
        {
            //TODO DEADLINE 1.C: Parse the column's name and type from a string generated by AsText()
            
            

            DataType tipo = DataType.String;
            
            string[] values = value.Split(Delimiter); 
            string nombre = Decode(values[0]); 


            if (values[1] == "String")
            {
                tipo = DataType.String;
            }
            else if (values[1] == "Int")
            {
                tipo = DataType.Int;
            }
            else if (values[1] == "Double")
            {
                tipo = DataType.Double;
            }
            return new ColumnDefinition(tipo , nombre);
                   
        }
    }
}
